### PR TITLE
Work with NumPy arrays instead of using Map.

### PR DESCRIPTION
**Pull request by HexDecimal**
Here's one example of handling tiles as a structured array.

Doing this elegantly is something I still have trouble with, NumPy arrays don't work with type hinting and you can't build the scalars (`floor` and `wall` in this case) using named parameters without a custom helper function.

I'd like some discussion on this before merging is even considered.  Are you able to tell what the new code does?

### CODE REVIEW

**Comment by HexDecimal** [comment]
I guess the worst case scenario is that `walkable` and `transparent` can be implemented similar to `tcod.map.Map` and then the rest of the code can stay the same but without sub-classing Map.

**Comment by TStand90** [comment]
As someone who hasn't worked with numpy, I think I understand what's going on, for the most part. I'm unclear about what "3B" means in this line:

`graphic_dt = np.dtype([("ch", np.int32), ("fg", "3B"), ("bg", "3B")])`

I think we should move everything except the GameMap class into a new file, maybe "tile_types.py" which "game_map.py" imports from.

My worry about going this route will be the added complexity for the beginner Python programmer. I suppose the tutorial's text could just hand-wave this part away, and tell the user to look into numpy if the reader wants to.

**Comment by HexDecimal** [comment]
> graphic_dt = np.dtype([("ch", np.int32), ("fg", "3B"), ("bg", "3B")])

`"3B"`" means 3 unsigned bytes.  Pretty much your standard RGB color type.  All specifics on NumPy dtypes are [in the documentation](https://numpy.org/doc/stable/reference/arrays.dtypes.html).

A dtype made from a  list of tuples is a "structured type", equivalent to a C struct such as:
```c
struct graphic_dt {
  int32_t ch;
  uint8_t fg[3];
  uint8_t bg[3];
}
```
This matches arrays like [Console.tiles_rgb](https://python-tcod.readthedocs.io/en/latest/tcod/console.html#tcod.console.Console.tiles_rgb) close enough that you can assign to that attribute from an array made with this type.

NumPy isn't all complex, but it's a large library with a lot of variation.  There are some very easy to use helper functions like [np.ndindex](https://numpy.org/doc/stable/reference/generated/numpy.ndindex.html#numpy.ndindex) and [np.ndenumerate](https://numpy.org/doc/stable/reference/generated/numpy.ndenumerate.html), and the harder to use functions become understandable as you use them.

If you understand C's ternary operator `out = cond ? a : b` then you can understand `out = np.where(cond, a, b)`.  [np.select](https://numpy.org/doc/stable/reference/generated/numpy.select.html) could be described as an `if..elif..else` chain.  These kinds of things could be clarified in a tutorial like this one, and I could write the explanations if you have trouble.

**Comment by HexDecimal** [comment]
I've committed a `tile_types.py` module, added a helper function, and added more documentation.

**Comment by HexDecimal** [comment]
I feel more confident with this version.  I think this can be merged, but if you still have any hesitation then I want to hear it first.

**Comment by HexDecimal** [comment]
I've been using a "dark" attribute since I know that later the tutorial will be making a distinction between lit and unlit tile graphics, but if you want I could change it to be more generic and then split it into separate light and dark graphics in a later part of the tutorial.

**Comment by TStand90** [comment]
This is great, thanks for all your hard work! I feel confident about merging this in. The tutorial text can explain the "dark" attribute, so I think it's good as is.

Quick question about Entity rendering: What's the benefit of using "tiles_rgb" over just "print"?

**Comment by HexDecimal** [comment]
It's probably best to show with a benchmark.

Here's some `pytest-benchmark` tests:
```python
from itertools import product

import tcod
import numpy as np

console_1 = tcod.Console(80, 24)
console_2 = tcod.Console(80, 24)


def test_print_once(benchmark):
    def test(console):
        console.print(0, 0, "@", (255, 255, 255))

    benchmark(test, console_1)


def test_numpy_set_once_python(benchmark):
    def test(console):
        console.tiles_rgb[["ch", "bg"]][0, 0] = ord("@"), (255, 255, 255)

    benchmark(test, console_1)


def test_numpy_set_once_scalar(benchmark):
    def test(console, value):
        console.tiles_rgb[["ch", "bg"]][0, 0] = value

    value = np.zeros(1, dtype=[("ch", np.intc), ("fg", "3B")])
    value[0] = ord("@"), (255, 255, 255)
    benchmark(test, console_1, value)


def test_print_all_ndindex(benchmark):
    def test(console):
        for y, x in np.ndindex(console.height, console.width):
            console.print(x, y, "@", (255, 255, 255))

    benchmark(test, console_1)


def test_print_all_range(benchmark):
    def test(console):
        for y in range(console.height):
            for x in range(console.width):
                console.print(x, y, "@", (255, 255, 255))

    benchmark(test, console_1)


def test_print_all_product(benchmark):
    def test(console):
        for y, x in product(range(console.height), range(console.width)):
            console.print(x, y, "@", (255, 255, 255))

    benchmark(test, console_1)


def test_numpy_broadcast(benchmark):
    def test(console):
        console.tiles_rgb[["ch", "bg"]] = ord("@"), (255, 255, 255)

    benchmark(test, console_1)


def test_numpy_copy(benchmark):
    def test(dest, source):
        dest.tiles_rgb[["ch", "bg"]] = source.tiles_rgb[["ch", "bg"]]

    benchmark(test, console_1, console_2)

```
Results:
```
============================= test session starts =============================
platform win32 -- Python 3.8.0, pytest-5.4.2, py-1.8.0, pluggy-0.13.1
benchmark: 3.2.3 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=5 calibration_precision=10 warmup=False warmup_iterations=100000)

------------------------------------------------------------------------------------------------ benchmark: 8 tests ------------------------------------------------------------------------------------------------
Name (time in us)                     Min                    Max                  Mean              StdDev                Median                 IQR            Outliers           OPS            Rounds  Iterations
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_print_once                    3.5350 (1.0)         295.4340 (1.0)          4.1240 (1.0)        3.3572 (1.0)          3.9290 (1.0)        0.0010 (1.0)     484;16376  242,484.4258 (1.0)       94274           1
test_numpy_set_once_scalar         5.5000 (1.56)      1,841.3540 (6.23)         6.3554 (1.54)       7.8247 (2.33)         5.8930 (1.50)       0.3930 (393.00)   634;2788  157,346.2799 (0.65)     102638           1
test_numpy_set_once_python         7.4640 (2.11)        563.7590 (1.91)         8.3391 (2.02)       6.4577 (1.92)         7.8570 (2.00)       0.0010 (1.0)     619;16397  119,917.5649 (0.49)      63636           1
test_numpy_copy                   31.4290 (8.89)      6,580.0800 (22.27)       34.5905 (8.39)      35.6792 (10.63)       32.2150 (8.20)       0.3930 (393.00)   868;9112   28,909.7006 (0.12)      69547           1
test_numpy_broadcast              33.0000 (9.34)     12,323.7510 (41.71)       36.2197 (8.78)      53.8063 (16.03)       33.3940 (8.50)       0.3940 (394.00)   661;7706   27,609.2776 (0.11)      63636           1
test_print_all_range           5,721.6720 (>1000.0)   9,419.7000 (31.88)    6,088.9914 (>1000.0)  400.1636 (119.20)   5,986.4620 (>1000.0)  302.1123 (>1000.0)     73;53      164.2308 (0.00)        839           1
test_print_all_product         5,818.3160 (>1000.0)  24,191.3880 (81.88)    6,160.5726 (>1000.0)  710.4464 (211.62)   6,080.7500 (>1000.0)  279.1295 (>1000.0)     20;34      162.3226 (0.00)        787           1
test_print_all_ndindex         8,031.7120 (>1000.0)  11,632.7030 (39.37)    8,453.9148 (>1000.0)  360.3961 (107.35)   8,375.0750 (>1000.0)  222.7540 (>1000.0)     39;33      118.2884 (0.00)        577           1
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Legend:
  Outliers: 1 Standard Deviation from Mean; 1.5 IQR (InterQuartile Range) from 1st Quartile and 3rd Quartile.
  OPS: Operations Per Second, computed as 1 / Mean
============================= 8 passed in 27.90s ==============================
```
I honestly did not expect the single-print to be faster than the single-array-set tests, but I did expect the print-over-every-tile tests to tank hard, which they did.

`Console.tiles_rgb` scales much better than `Console.print`, but turns out `Console.print` was somehow able to convert Python types to C faster than NumPy.  So it might be a good idea to print entities with `Console.print` after all (unless they could be batched, but even I'd say that's outside the scope of this tutorial.)

I've reverted the relevant code to use `Console.print` again.

**Comment by TStand90** [comment]
Interesting, I thought `Console.tiles_rgb` would be faster on entities as well, but I thought that the performance gain might not be worth the extra complication. I agree that "batching" the entities is probably outside the scope of a beginner tutorial.

Thanks for looking into that.

**Pull request merged**
